import os
import smtplib
import logging
import requests
from bs4 import BeautifulSoup
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta

# Configuring the logging
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s')

BASE_URL = "https://pswsnetwork.eng.ua.edu"

def fetch_psws_summary():
    """
    Scrapes all pages and groups observations by station with links.
    Returns (station_summary_dict, filtered_url_for_footer)
    """
    yesterday_date = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
    list_url = f"{BASE_URL}/observations/observation_list/"
    
    # This is the exact URL the bot uses for the first page
    filtered_url = f"{list_url}?station=&startDate__gte={yesterday_date}&endDate__lte={yesterday_date}"
    
    station_summary = {}
    page_num = 1
    max_pages = 15

    while page_num <= max_pages:
        query_url = f"{filtered_url}&page={page_num}"
        
        try:
            logging.info(f"Scraping Page {page_num}...")
            response = requests.get(query_url, timeout=30)
            if response.status_code != 200:
                break
                
            soup = BeautifulSoup(response.text, 'html.parser')
            table = soup.find('table', {'class': 'obsTable'})
            if not table:
                break

            rows = table.find('tbody').find_all('tr')
            if not rows:
                break
            
            for row in rows:
                cols = row.find_all('td')
                if len(cols) >= 6:
                    station_cell = cols[2]
                    station_link_tag = station_cell.find('a')
                    
                    station_name = station_cell.get_text(strip=True)
                    station_url = f"{BASE_URL}{station_link_tag['href']}" if station_link_tag else "#"

                    if station_name not in station_summary:
                        station_summary[station_name] = {'link': station_url, 'count': 0}
                    
                    station_summary[station_name]['count'] += 1

            # Check for "Next" page
            pagination = soup.find('ul', {'class': 'pagination'})
            if not pagination or f"page={page_num + 1}" not in str(pagination):
                break
                
            page_num += 1

        except Exception as e:
            logging.error(f"Error on page {page_num}: {str(e)}")
            break
            
    return station_summary, filtered_url

def send_email(email_config, summary, filtered_url):
    try:
        yesterday_str = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
        
        msg = MIMEMultipart()
        msg['From'] = email_config['sender_email']
        msg['To'] = email_config['receiver_email']
        msg['Subject'] = f"PSWS Summary: {yesterday_str}"
        
        html_rows = ""
        total_obs = 0
        sorted_stations = sorted(summary.items())

        for station, data in sorted_stations:
            total_obs += data['count']
            html_rows += f"<li><a href='{data['link']}'>{station}</a>: <b>{data['count']}</b> observations</li>"

        if not summary:
            html_body = f"<p>No activity recorded on the PSWS network for {yesterday_str}.</p>"
        else:
            html_body = f"""
            <html>
            <body style="font-family: sans-serif; line-height: 1.6; color: #333;">
                <div style="background-color: #333; padding: 10px; text-align: center;">
                    <a href="{BASE_URL}" style="color: white; text-decoration: none; font-weight: bold;">
                        Visit PSWS Central Control System
                    </a>
                </div>
                
                <h2 style="color: #04AA6D;">Daily Network Overview</h2>
                <p>For <b>{yesterday_str}</b>, the network recorded a total of <b>{total_obs}</b> observations across <b>{len(summary)}</b> stations.</p>
                
                <ul style="list-style-type: square;">
                    {html_rows}
                </ul>
                
                <div style="margin-top: 20px; padding: 15px; background-color: #f9f9f9; border-left: 5px solid #04AA6D;">
                    <p style="margin: 0;"><b>Want to see the full list?</b></p>
                    <p style="margin: 5px 0 0 0;"><a href="{filtered_url}">View all files on the Observation List page &rarr;</a></p>
                </div>
                
                <p style="font-size: 0.8em; color: #999; margin-top: 30px;">
                    This is an automated report generated by your GitHub Bot.
                </p>
            </body>
            </html>
            """
        
        msg.attach(MIMEText(html_body, 'html'))
      
        server = smtplib.SMTP(email_config['smtp_server'], email_config['smtp_port'], timeout=15)
        server.starttls() 
        
        with server:
            server.login(email_config['sender_email'], email_config['smtp_password']) 
            server.send_message(msg)
            logging.info("HTML Email with navigation links sent successfully")
          
    except Exception as e: 
        logging.error(f"Failed to send email: {str(e)}")
        raise

if __name__ == "__main__":
    try:
        config = {
            'sender_email': os.getenv('SENDER_EMAIL'),
            'receiver_email': os.getenv('RECEIVER_EMAIL'),
            'smtp_server': os.getenv('SMTP_SERVER'),
            'smtp_port': os.getenv('SMTP_PORT'),
            'smtp_password': os.getenv('SMTP_PASSWORD')
        }

        if not all(v for v in config.values()):
            raise ValueError("Missing environment variables.")

        # Now returns the data AND the link
        summary_data, observation_link = fetch_psws_summary()
        send_email(config, summary_data, observation_link)
            
    except Exception as e:
        logging.error(f"Critical Bot Failure: {str(e)}")
        raise
