import os
import smtplib
import logging
import requests
from bs4 import BeautifulSoup
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta

# Configuring the logging
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s')

BASE_URL = "https://pswsnetwork.eng.ua.edu"

def fetch_psws_summary():
    """
    Scrapes all pages and groups observations by station with links.
    """
    yesterday_date = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
    list_url = f"{BASE_URL}/observations/observation_list/"
    
    # Structure: { "Station Name": {"link": "url", "count": X} }
    station_summary = {}
    page_num = 1
    max_pages = 15

    while page_num <= max_pages:
        query_url = f"{list_url}?station=&startDate__gte={yesterday_date}&endDate__lte={yesterday_date}&page={page_num}"
        
        try:
            logging.info(f"Scraping Page {page_num}...")
            response = requests.get(query_url, timeout=30)
            if response.status_code != 200:
                break
                
            soup = BeautifulSoup(response.text, 'html.parser')
            table = soup.find('table', {'class': 'obsTable'})
            if not table:
                break

            rows = table.find('tbody').find_all('tr')
            if not rows:
                break
            
            for row in rows:
                cols = row.find_all('td')
                if len(cols) >= 6:
                    station_cell = cols[2]
                    station_link_tag = station_cell.find('a')
                    
                    station_name = station_cell.get_text(strip=True)
                    # Create absolute link to the station's analysis page
                    station_url = f"{BASE_URL}{station_link_tag['href']}" if station_link_tag else "#"

                    if station_name not in station_summary:
                        station_summary[station_name] = {'link': station_url, 'count': 0}
                    
                    station_summary[station_name]['count'] += 1

            # Check for "Next" page
            pagination = soup.find('ul', {'class': 'pagination'})
            if not pagination or f"page={page_num + 1}" not in str(pagination):
                break
                
            page_num += 1

        except Exception as e:
            logging.error(f"Error on page {page_num}: {str(e)}")
            break
            
    return station_summary

def send_email(email_config, summary):
    try:
        yesterday_str = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
        
        msg = MIMEMultipart()
        msg['From'] = email_config['sender_email']
        msg['To'] = email_config['receiver_email']
        msg['Subject'] = f"PSWS Summary: {yesterday_str}"
        
        # Build HTML content
        html_rows = ""
        total_obs = 0
        
        # Sort stations alphabetically for the email
        sorted_stations = sorted(summary.items())

        for station, data in sorted_stations:
            total_obs += data['count']
            html_rows += f"<li><a href='{data['link']}'>{station}</a>: <b>{data['count']}</b> observations</li>"

        if not summary:
            html_body = f"<p>No activity recorded on the PSWS network for {yesterday_str}.</p>"
        else:
            html_body = f"""
            <html>
            <body style="font-family: sans-serif; color: #333;">
                <h2 style="color: #04AA6D;">Daily Network Overview</h2>
                <p>For <b>{yesterday_str}</b>, the network recorded a total of <b>{total_obs}</b> observations across <b>{len(summary)}</b> stations.</p>
                <hr>
                <ul>
                    {html_rows}
                </ul>
                <br>
                <p style="font-size: 0.8em; color: #666;">Generated by your PSWS GitHub Bot</p>
            </body>
            </html>
            """
        
        msg.attach(MIMEText(html_body, 'html'))
      
        server = smtplib.SMTP(email_config['smtp_server'], email_config['smtp_port'], timeout=15)
        server.starttls() 
        
        with server:
            server.login(email_config['sender_email'], email_config['smtp_password']) 
            server.send_message(msg)
            logging.info("HTML Email sent successfully")
          
    except Exception as e: 
        logging.error(f"Failed to send email: {str(e)}")
        raise

if __name__ == "__main__":
    try:
        config = {
            'sender_email': os.getenv('SENDER_EMAIL'),
            'receiver_email': os.getenv('RECEIVER_EMAIL'),
            'smtp_server': os.getenv('SMTP_SERVER'),
            'smtp_port': os.getenv('SMTP_PORT'),
            'smtp_password': os.getenv('SMTP_PASSWORD')
        }

        # Validate config
        if not all(v for v in config.values()):
            raise ValueError("Missing environment variables.")

        summary_data = fetch_psws_summary()
        send_email(config, summary_data)
            
    except Exception as e:
        logging.error(f"Critical Bot Failure: {str(e)}")
        raise
